[profile.default]
src = "contracts/src"
out = "contracts/out"
test = "contracts/test"
libs = ["contracts/lib"]
# via_ir = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config